import { createGroq } from "@ai-sdk/groq"
import type { LanguageModelV2 } from "@ai-sdk/provider"
import { LanguageModel } from "ai"

export class AiUnavailableError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "AiUnavailableError"
  }
}

export const DEFAULT_AI_MODEL = "llama-3.3-70b-versatile"

export function getModelId(): string {
  const provider = process.env.AI_PROVIDER || "groq"
  if (provider === "mock" || provider === "mock-fail") {
    return provider
  }
  // unknown providers never reach the usage ledger — getModel() throws first
  return process.env.AI_MODEL || DEFAULT_AI_MODEL
}

// Canned outputs for the deterministic mock provider. Structured
// capabilities get schema-conforming JSON; text capabilities get prose.
const CANNED_OUTPUTS: Record<string, string> = {
  listing: JSON.stringify({
    title: "Handwoven Ankara Tote Bag",
    description:
      "A mock product description generated by the deterministic test provider.",
    tags: ["ankara", "tote", "handmade"],
    seo_title: "Handwoven Ankara Tote Bag | How's u",
    seo_description: "Mock SEO description for the Ankara tote.",
  }),
  pricing: JSON.stringify({
    suggested_price: 12000,
    floor_price: 9000,
    ceiling_price: 15000,
    reasoning: "Mock reasoning based on marketplace price statistics.",
  }),
  marketing: JSON.stringify({
    brand_voice: "Warm, confident, and proudly local.",
    promo_ideas: ["Mock promo idea one", "Mock promo idea two"],
    bundle_suggestions: ["Mock bundle suggestion"],
  }),
  insights: "Mock insight: your best seller this month is the Demo Ankara Tote.",
  accounting:
    "Mock digest: revenue, commission deducted, and net earnings summarized.",
  brief:
    "Mock brief: revenue and net summarized from the deterministic numbers.",
  recommendations: JSON.stringify({
    opportunities: [
      { action: "bundle", sku: "A + B", explanation: "Mock explanation for the bundle." },
    ],
  }),
}

// Every capability's system prompt begins with "[capability:<name>]" so the
// mock can return the right canned shape.
function detectCapability(prompt: unknown): string {
  const serialized = JSON.stringify(prompt)
  const match = /\[capability:(\w+)\]/.exec(serialized)
  return match?.[1] ?? "insights"
}

// Hand-rolled LanguageModelV2 instead of `ai/test`'s MockLanguageModelV2:
// that entrypoint requires msw/vitest, which cannot load in Medusa's
// CommonJS runtime. Behavior is identical for doGenerate.
function buildMockModel(fail: boolean): LanguageModelV2 {
  return {
    specificationVersion: "v2",
    provider: "mock",
    modelId: "mock-model",
    supportedUrls: {},
    doGenerate: async (options) => {
      // expose the exact prompt for isolation assertions in tests
      ;(globalThis as any).__howsuLastAiPrompt = JSON.stringify(options.prompt)

      if (fail) {
        throw new AiUnavailableError("mock provider forced failure")
      }

      const capability = detectCapability(options.prompt)

      return {
        finishReason: "stop" as const,
        usage: { inputTokens: 10, outputTokens: 20, totalTokens: 30 },
        content: [
          { type: "text" as const, text: CANNED_OUTPUTS[capability] },
        ],
        warnings: [],
      }
    },
    doStream: async () => {
      throw new AiUnavailableError("mock provider does not support streaming")
    },
  }
}

export function getModel(): LanguageModel {
  const provider = process.env.AI_PROVIDER || "groq"

  if (provider === "mock") {
    return buildMockModel(false)
  }
  if (provider === "mock-fail") {
    return buildMockModel(true)
  }
  if (provider !== "groq") {
    throw new AiUnavailableError(`Unknown AI_PROVIDER "${provider}"`)
  }

  const apiKey = process.env.GROQ_API_KEY
  if (!apiKey) {
    throw new AiUnavailableError(
      "GROQ_API_KEY is not configured — AI features are disabled"
    )
  }

  const groq = createGroq({ apiKey })
  return groq(process.env.AI_MODEL || DEFAULT_AI_MODEL)
}
